version: '3.8'
services:
  file-service:
    build:
      context: ./file-service
    ports:
      - "8082:8082"
    environment:
      METADATA_SERVICE_URL: http://metadata-service:8083
    depends_on:
      - metadata-service
    command: ["go", "run", "main.go"]

  metadata-service:
    build:
      context: ./metadata-service
    ports:
      - "8083:8083"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_metadata
    depends_on:
      - postgres
    command: ["go", "run", "main.go"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_metadata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d file_metadata"]
      interval: 10s
      timeout: 5s
      retries: 5
