version: '3.8'

services:
  file-service:
    build:
      context: ./file-service
    ports:
      - "8082:8082"
    environment:
      METADATA_SERVICE_URL: http://metadata-service:8083  # Service-to-service API communication
    depends_on:
      - metadata-service
    command: ["./main"]

  metadata-service:
    build:
      context: ./metadata-service
    ports:
      - "8083:8083"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_metadata
    depends_on:
      postgres:
        condition: service_healthy  # Wait for PostgreSQL to be ready
    command: ["./main"]

  postgres:
    image: bitnami/postgresql:17.3.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_metadata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d file_metadata"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Named volume for PostgreSQL persistence
